### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Roman-Blinkov** [civo/civostatsd#1]
Hi!
I got this in logs:

```
Mar 27 05:10:21 minion2 civostatsd[1175]: CPU: 0.00%, Disk: 11.04%, Memory: 28.40%
Mar 27 05:12:36 minion2 civostatsd[1175]: CPU: 1.00%, Disk: 11.04%, Memory: 28.39%
Mar 27 05:13:21 minion2 civostatsd[1175]: CPU: 0.00%, Disk: 11.04%, Memory: 28.39%
Mar 27 05:15:37 minion2 civostatsd[1175]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 27 05:15:37 minion2 civostatsd[1175]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47feb3]
Mar 27 05:15:37 minion2 civostatsd[1175]: goroutine 1 [running]:
Mar 27 05:15:37 minion2 civostatsd[1175]: panic(0x616900, 0xc42000a050)
Mar 27 05:15:37 minion2 civostatsd[1175]:         /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
Mar 27 05:15:37 minion2 civostatsd[1175]: github.com/absolutedevops/civostatsd/send.ToAPI(0xc4200b0720, 0x14, 0xc420012ed0, 0x24, 0x4130931900000000, 0x41e318a7)
Mar 27 05:15:37 minion2 civostatsd[1175]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/send/main.go:26 +0x823
Mar 27 05:15:37 minion2 civostatsd[1175]: main.main()
Mar 27 05:15:37 minion2 civostatsd[1175]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/main.go:46 +0x693
Mar 27 05:15:37 minion2 systemd[1]: civostatsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 27 05:15:37 minion2 systemd[1]: civostatsd.service: Failed with result 'exit-code'.
```

I "quickfixed" this using `systemctl start civostatsd`
Thank you!

**Comment by Roman-Blinkov** [comment]
```
minion7:
    Apr 07 11:06:29 minion7 civostatsd[1355]: CPU: 0.00%, Disk: 18.25%, Memory: 33.96%
    Apr 07 11:06:43 minion7 civostatsd[1355]: panic: runtime error: invalid memory address or nil pointer dereference
    Apr 07 11:06:43 minion7 civostatsd[1355]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47feb3]
    Apr 07 11:06:43 minion7 civostatsd[1355]: goroutine 1 [running]:
    Apr 07 11:06:43 minion7 civostatsd[1355]: panic(0x616900, 0xc42000a050)
    Apr 07 11:06:43 minion7 civostatsd[1355]:         /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
    Apr 07 11:06:43 minion7 civostatsd[1355]: github.com/absolutedevops/civostatsd/send.ToAPI(0xc4200a8720, 0x14, 0xc420012ed0, 0x24, 0x4191ff4900000000, 0x4207d954)
    Apr 07 11:06:43 minion7 civostatsd[1355]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/send/main.go:26 +0x823
    Apr 07 11:06:43 minion7 civostatsd[1355]: main.main()
    Apr 07 11:06:43 minion7 civostatsd[1355]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/main.go:46 +0x693
    Apr 07 11:06:43 minion7 systemd[1]: civostatsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
    Apr 07 11:06:43 minion7 systemd[1]: civostatsd.service: Failed with result 'exit-code'.

minion6:
    Apr 07 11:08:34 minion6 civostatsd[979]: panic: runtime error: invalid memory address or nil pointer dereference
    Apr 07 11:08:34 minion6 civostatsd[979]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47feb3]
    Apr 07 11:08:34 minion6 civostatsd[979]: goroutine 1 [running]:
    Apr 07 11:08:34 minion6 civostatsd[979]: panic(0x616900, 0xc42000a050)
    Apr 07 11:08:34 minion6 civostatsd[979]:         /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1    Apr 07 11:08:34 minion6 civostatsd[979]: github.com/absolutedevops/civostatsd/send.ToAPI(0xc4200b0720, 0x14, 0xc420012ed0, 0x24, 0x414000fd00000000, 0x4212abd8)
    Apr 07 11:08:34 minion6 civostatsd[979]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/send/main.go:26 +0x823
    Apr 07 11:08:34 minion6 civostatsd[979]: main.main()
    Apr 07 11:08:34 minion6 civostatsd[979]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/main.go:46 +0x693
    Apr 07 11:08:34 minion6 systemd[1]: civostatsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
    Apr 07 11:08:34 minion6 systemd[1]: civostatsd.service: Failed with result 'exit-code'.

minion5:
    Apr 07 11:12:29 minion5 civostatsd[1141]: panic: runtime error: invalid memory address or nil pointer dereference
    Apr 07 11:12:29 minion5 civostatsd[1141]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47feb3]
    Apr 07 11:12:29 minion5 civostatsd[1141]: goroutine 1 [running]:
    Apr 07 11:12:29 minion5 civostatsd[1141]: panic(0x616900, 0xc42000a050)
    Apr 07 11:12:29 minion5 civostatsd[1141]:         /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
    Apr 07 11:12:29 minion5 civostatsd[1141]: github.com/absolutedevops/civostatsd/send.ToAPI(0xc4200b0720, 0x14, 0xc420012ed0, 0x24, 0x41bf0e2300000000, 0x420d1419)
    Apr 07 11:12:29 minion5 civostatsd[1141]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/send/main.go:26 +0x823
    Apr 07 11:12:29 minion5 civostatsd[1141]: main.main()
    Apr 07 11:12:29 minion5 civostatsd[1141]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/main.go:46 +0x693
    Apr 07 11:12:29 minion5 systemd[1]: civostatsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
    Apr 07 11:12:29 minion5 systemd[1]: civostatsd.service: Failed with result 'exit-code'.

login:
    Apr 07 11:08:19 login civostatsd[1164]: panic: runtime error: invalid memory address or nil pointer dereference
    Apr 07 11:08:19 login civostatsd[1164]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47feb3]
    Apr 07 11:08:19 login civostatsd[1164]: goroutine 1 [running]:
    Apr 07 11:08:19 login civostatsd[1164]: panic(0x616900, 0xc42000a050)
    Apr 07 11:08:19 login civostatsd[1164]:         /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
    Apr 07 11:08:19 login civostatsd[1164]: github.com/absolutedevops/civostatsd/send.ToAPI(0xc4200b0720, 0x14, 0xc420012ed0, 0x24, 0x41d7a5d400000000, 0x421e5212)
    Apr 07 11:08:19 login civostatsd[1164]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/send/main.go:26 +0x823
    Apr 07 11:08:19 login civostatsd[1164]: main.main()
    Apr 07 11:08:19 login civostatsd[1164]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/main.go:46 +0x693
    Apr 07 11:08:19 login systemd[1]: civostatsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
    Apr 07 11:08:19 login systemd[1]: civostatsd.service: Failed with result 'exit-code'.

postgres:
    Apr 07 11:09:16 postgres civostatsd[1150]: panic: runtime error: invalid memory address or nil pointer dereference
    Apr 07 11:09:16 postgres civostatsd[1150]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47feb3]
    Apr 07 11:09:16 postgres civostatsd[1150]: goroutine 1 [running]:
    Apr 07 11:09:16 postgres civostatsd[1150]: panic(0x616900, 0xc42000a050)
    Apr 07 11:09:16 postgres civostatsd[1150]:         /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
    Apr 07 11:09:16 postgres civostatsd[1150]: github.com/absolutedevops/civostatsd/send.ToAPI(0xc4200b0720, 0x14, 0xc420012ed0, 0x24, 0x41c497af00000000, 0x41fee68e)
    Apr 07 11:09:16 postgres civostatsd[1150]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/send/main.go:26 +0x823
    Apr 07 11:09:16 postgres civostatsd[1150]: main.main()
    Apr 07 11:09:16 postgres civostatsd[1150]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/main.go:46 +0x693
    Apr 07 11:09:16 postgres systemd[1]: civostatsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT    Apr 07 11:09:16 postgres systemd[1]: civostatsd.service: Failed with result 'exit-code'.

minion4:
    Apr 07 11:07:32 minion4 civostatsd[1180]: panic: runtime error: invalid memory address or nil pointer dereference
    Apr 07 11:07:32 minion4 civostatsd[1180]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47feb3]
    Apr 07 11:07:32 minion4 civostatsd[1180]: goroutine 1 [running]:
    Apr 07 11:07:32 minion4 civostatsd[1180]: panic(0x616900, 0xc42000a050)
    Apr 07 11:07:32 minion4 civostatsd[1180]:         /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
    Apr 07 11:07:32 minion4 civostatsd[1180]: github.com/absolutedevops/civostatsd/send.ToAPI(0xc4200b0720, 0x14, 0xc420012ed0, 0x24, 0x41cef84f00000000, 0x41fd824c)
    Apr 07 11:07:32 minion4 civostatsd[1180]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/send/main.go:26 +0x823
    Apr 07 11:07:32 minion4 civostatsd[1180]: main.main()
    Apr 07 11:07:32 minion4 civostatsd[1180]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/main.go:46 +0x693
    Apr 07 11:07:32 minion4 systemd[1]: civostatsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
    Apr 07 11:07:32 minion4 systemd[1]: civostatsd.service: Failed with result 'exit-code'.

minion3:
    Apr 07 11:10:21 minion3 civostatsd[1166]: panic: runtime error: invalid memory address or nil pointer dereference
    Apr 07 11:10:21 minion3 civostatsd[1166]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47feb3]
    Apr 07 11:10:21 minion3 civostatsd[1166]: goroutine 1 [running]:
    Apr 07 11:10:21 minion3 civostatsd[1166]: panic(0x616900, 0xc42000a050)
    Apr 07 11:10:21 minion3 civostatsd[1166]:         /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
    Apr 07 11:10:21 minion3 civostatsd[1166]: github.com/absolutedevops/civostatsd/send.ToAPI(0xc4200b0720, 0x14, 0xc420012ed0, 0x24, 0x419fd9b800000000, 0x42030a96)
    Apr 07 11:10:21 minion3 civostatsd[1166]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/send/main.go:26 +0x823
    Apr 07 11:10:21 minion3 civostatsd[1166]: main.main()
    Apr 07 11:10:21 minion3 civostatsd[1166]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/main.go:46 +0x693
    Apr 07 11:10:21 minion3 systemd[1]: civostatsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
    Apr 07 11:10:21 minion3 systemd[1]: civostatsd.service: Failed with result 'exit-code'.

minion2:
    Apr 07 11:08:34 minion2 civostatsd[12105]: panic: runtime error: invalid memory address or nil pointer dereference
    Apr 07 11:08:34 minion2 civostatsd[12105]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47feb3]
    Apr 07 11:08:34 minion2 civostatsd[12105]: goroutine 1 [running]:
    Apr 07 11:08:34 minion2 civostatsd[12105]: panic(0x616900, 0xc42000a050)
    Apr 07 11:08:34 minion2 civostatsd[12105]:         /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
    Apr 07 11:08:34 minion2 civostatsd[12105]: github.com/absolutedevops/civostatsd/send.ToAPI(0xc4200a86e0, 0x14, 0xc420012ed0, 0x24, 0x41d701a300000000, 0x41ea4676)
    Apr 07 11:08:34 minion2 civostatsd[12105]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/send/main.go:26 +0x823
    Apr 07 11:08:34 minion2 civostatsd[12105]: main.main()
    Apr 07 11:08:34 minion2 civostatsd[12105]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/main.go:46 +0x693
    Apr 07 11:08:34 minion2 systemd[1]: civostatsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
    Apr 07 11:08:34 minion2 systemd[1]: civostatsd.service: Failed with result 'exit-code'.

minion1:
    Apr 07 11:07:55 minion1 civostatsd[1136]: panic: runtime error: invalid memory address or nil pointer dereference
    Apr 07 11:07:55 minion1 civostatsd[1136]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47feb3]
    Apr 07 11:07:55 minion1 civostatsd[1136]: goroutine 1 [running]:
    Apr 07 11:07:55 minion1 civostatsd[1136]: panic(0x616900, 0xc42000a050)
    Apr 07 11:07:55 minion1 civostatsd[1136]:         /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
    Apr 07 11:07:55 minion1 civostatsd[1136]: github.com/absolutedevops/civostatsd/send.ToAPI(0xc4200b0720, 0x14, 0xc420012ed0, 0x24, 0x41c08b0900000000, 0x41e056ed)
    Apr 07 11:07:55 minion1 civostatsd[1136]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/send/main.go:26 +0x823
    Apr 07 11:07:55 minion1 civostatsd[1136]: main.main()
    Apr 07 11:07:55 minion1 civostatsd[1136]:         /Users/andy/Code/go/src/github.com/absolutedevops/civostatsd/main.go:46 +0x693
    Apr 07 11:07:55 minion1 systemd[1]: civostatsd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
    Apr 07 11:07:55 minion1 systemd[1]: civostatsd.service: Failed with result 'exit-code'.



```
